fetch('https://studio.code.org/v2/certificate', {
    headers: {
        accept: 'application/json, text/javascript, */*; q=0.01',
        'accept-language': 'en-US,en;q=0.9',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        priority: 'u=1, i',
        'sec-ch-ua': '"Not)A;Brand";v="8", "Chromium";v="138", "Brave";v="138"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'sec-gpc': '1',
        'x-csrf-token': 'hO8PUB0fhhVHTiC4lPS2L4I5Pn8W_ysVUegkYer5X1NALfB8Nbef74phAU4DmR_qpSMppnxW5bE9ytopbLB2Bw',
        'x-newrelic-id': 'UQYGVVBQGwAHXFZRAQU=',
        'x-requested-with': 'XMLHttpRequest',
        cookie: 'language_=en-US; _learn_session=ee6fac656a4f100ed1fc822b45163f31; AMP_MKTG_f6db63e17b=JTdCJTIycmVmZXJyZXIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmNvZGUub3JnJTJGJTIyJTJDJTIycmVmZXJyaW5nX2RvbWFpbiUyMiUzQSUyMmNvZGUub3JnJTIyJTdE; mute_music=true; hide_swipe_overlay=true; AMP_f6db63e17b=JTdCJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJkZXZpY2VJZCUyMiUzQSUyMmUyYjY5Yjc1LWU1ZDEtNGNmNC04MzE1LTk4YmU1NWI3MTgyNiUyMiUyQyUyMmxhc3RFdmVudFRpbWUlMjIlM0ExNzUyNTA2MzU5MDQzJTJDJTIyc2Vzc2lvbklkJTIyJTNBMTc1MjUwNTEyODM1NiU3RA==; AWSALB=bNtFly06+Gl+k3IJOCphyy6xAlwah/iDYKJSc8i3AfBWoRF+jqXdMiyAUgkJQBXEZ908yxzLt/YgtmEKSokBy5Ag5mYlQ5uSOWymqieIsWxqh3GT9JVy98k1Nzus; AWSALBCORS=bNtFly06+Gl+k3IJOCphyy6xAlwah/iDYKJSc8i3AfBWoRF+jqXdMiyAUgkJQBXEZ908yxzLt/YgtmEKSokBy5Ag5mYlQ5uSOWymqieIsWxqh3GT9JVy98k1Nzus',
        Referer: 'https://studio.code.org/congrats?i=_1_1f8b895e66e5da26acc9be747ac0162c&s=c3RhcndhcnM=',
    },
    body: 'session_s=_1_1f8b895e66e5da26acc9be747ac0162c&name_s=Mohammed+Mahmoud',
    method: 'POST',
});
